package editor.gui.dockables;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.List;

/**
 * Created by IntelliJ IDEA.
 * User: Peter
 * Date: 1/28/11
 * Time: 9:47 PM
 * Computer: Peterbjornx-PC.rootdomain.asn.local (192.168.178.27)
 */
public class EditorToolbar {
    private JButton heightLevelUpButton;
    private JButton heightLevelDownButton;
    private JToggleButton showAllHeightLevelButtons;
    private int ourHeightlevel = 0;
    private List<ChangeListener> listenerList = new LinkedList<ChangeListener>();
    private JPanel mainPane;

    public EditorToolbar() {
        heightLevelDownButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             */
            public void actionPerformed(ActionEvent e) {
                if (ourHeightlevel == 3) {
                    heightLevelUpButton.setEnabled(true);
                }
                ourHeightlevel--;
                if (ourHeightlevel < 0) {
                    ourHeightlevel = 0;
                    heightLevelDownButton.setEnabled(false);
                }
                for (ChangeListener l : listenerList)
                    l.stateChanged(null);
            }
        });
        heightLevelUpButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             */
            public void actionPerformed(ActionEvent e) {
                if (ourHeightlevel == 0) {
                    heightLevelDownButton.setEnabled(true);
                }
                ourHeightlevel++;
                if (ourHeightlevel > 3) {
                    ourHeightlevel = 3;
                    heightLevelUpButton.setEnabled(false);
                }
                for (ChangeListener l : listenerList)
                    l.stateChanged(null);
            }
        });
        showAllHeightLevelButtons.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                for (ChangeListener l : listenerList)
                    l.stateChanged(null);
            }
        });
    }

    public boolean addChangeListener(ChangeListener changeListener) {
        return listenerList.add(changeListener);
    }

    public boolean removeChangeListener(ChangeListener o) {
        return listenerList.remove(o);
    }

    public int getHeightlevel() {
        return ourHeightlevel;
    }

    public boolean getShowAllHLs() {
        return showAllHeightLevelButtons.isSelected();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public Component getMainPane() {
        return mainPane;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        heightLevelUpButton = new JButton();
        heightLevelUpButton.setText("HL+");
        mainPane.add(heightLevelUpButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        heightLevelDownButton = new JButton();
        heightLevelDownButton.setText("HL-");
        mainPane.add(heightLevelDownButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        mainPane.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        showAllHeightLevelButtons = new JToggleButton();
        showAllHeightLevelButtons.setText("AllHLs");
        mainPane.add(showAllHeightLevelButtons, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
